### ISSUE TITLE
Namespace conflict with nvidia libcu++

### ISSUE THREAD

**Issue by raplonu** [eyalroz/cuda-api-wrappers#256] opened 2021-08-19 01:52 UTC
I tried to use `cuda-api-wrappers` along with [`libcu++`](https://nvidia.github.io/libcudacxx/) and encountered several issues.

The most simple one occurs when including any `libcu++` header then `cuda/runtime_api.hpp` like so:

```c++
#include <cuda/atomic>
#include <cuda/runtime_api.hpp>

int main() {}
```

All errors come from `cuda-api-wrappers` and can be summarize as:

```bash
error: ‘XXX’ is not a member of ‘cuda::std’
```

Where XXX is a component of the `std` (std::string, std::logic_error).

Including in the invert order works unless it is a cuda source file. Doing

```Cuda
#include <cuda/runtime_api.hpp>
#include <cuda/atomic>

int main() {}
```

will produce errors from libuc++ header such as:

```bash
error: "cuda::std::detail" is ambiguous
```

The first issue can easily be resolve by appending `::` before each `std` symbol: `::std::string`.
However, the second issue may be harder to durably fix. Changing all occurrences of `detail` namespace by something else seems to resolve the issue.

A common solution for this kind of issue consist on wrapping one of the library but since `libcu++` is heavily templated and the `cuda-api-wrappers` is already a wrapper this solution is not practical.

**Comment by eyalroz** [comment] 2021-08-19 05:23
Can you give the simplest example of what triggers 
```
error: "cuda::std::detail" is ambiguous
```
?

**Comment by eyalroz** [comment] 2021-08-19 06:14
I can't reproduce the second kind of problem with your trivial program. Could it be that the resolving the first one also resolves the second one? Hmm.

**Comment by raplonu** [comment] 2021-08-19 07:07
> 1. (expletive) (expletive) NVIDIA people! I totally blame them for them for putting an `std` inside `cuda`.

Yeah, I agree, they played a dangerous game here. I feel sorry for you since there is no design flaw in your library but I don't think they gonna change that...


> I can't reproduce the second kind of problem with your trivial program. Could it be that the resolving the first one also resolves the second one? Hmm.

Did you tried to reproduce in a cuda source file ?

On your branch **master** I replaced every occurrences of `std::` by `::std::`, it fixed the first point (in a `.cpp` file, both include order).
But in a cuda (`.cu`) file, doing 

```cuda
#include <cuda/atomic>
#include <cuda/runtime_api.hpp>
```
Will point error in `cuda-api-wrappers` such as

```bash
cuda-api-wrappers/src/cuda/api/memory.hpp(190): error: "cuda::detail" is ambiguous
```

And 

```cuda
#include <cuda/runtime_api.hpp>
#include <cuda/atomic>
```
Will point error in `libcu++` such as

```bash
cuda/std/detail/__atomic(135): error: "cuda::std::detail" is ambiguous
```

In addition to the `::std::` fix, I replaced every occurrence of `detail` by `detail2`. It worked with both include order.

> 3. Please try the upcoming change to the development branch to address at least the first part of the problem.

I just tried with the **development** branch at 63f88888e91bf719c3e74b51002631164ab7a72d .
You indeed fix the fist issue mentioned, but the second one is still present.

**Comment by eyalroz** [comment] 2021-08-19 10:48
@raplonu : You're right, I only tried reproducing this in `.cpp` files.

Well, I suppose I could use `detail_` instead of `detail`. It won't hurt anything except my aesthetic sensibilities.

By the way - if you're already trying things out:

* Have you tried out my `driver-wrappers` branch? Which expands functionality quite a bit? I need to decide whether to have it replace the current code or release it as a separate alternative.
* Have you had any issues with the `development` branch? I want to merge my recent changes and make a new release.

**Comment by raplonu** [comment] 2021-08-20 01:56
> Well, I suppose I could use `detail_` instead of `detail`. It won't hurt anything except my aesthetic sensibilities.

I understand. I may have another idea... The thing is that we cannot be sure we won't have another conflict in the future.
The idea consist on changing your global namespace name. Let say from `cuda` to `cuda_wrap` ( or `eyalroz::cuda` like [ `nlohmann::json`](https://github.com/nlohmann/json/) ). But we can do that in multiple steps.

1- Let users explicitly use the new namespace.

```c++
#ifdef CUDA_WRAP_USE_NEW_NAMESPACE
#define CUDA_NAMESPACE cuda_wrap
#else
#define CUDA_NAMESPACE cuda
#endif
```

2- Deprecate the old namespace and let users explicitly use it.
3- Let users create an namespace alias `cuda` on their codebase.

I'm not used to deprecation procedure, their is probably a better approach.

> * Have you tried out my `driver-wrappers` branch? Which expands functionality quite a bit? I need to decide whether to have it replace the current code or release it as a separate alternative.

Not yet, I'm looking forward to use it. The NVRTC and cuStream read write support will be useful but I won't be able to test it anytime soon.

> * Have you had any issues with the `development` branch? I want to merge my recent changes and make a new release.

I'm gonna test it next week.

**Closed** 2021-08-20 07:39 UTC
Labels: task, resolved-on-development
