### ISSUE TITLE
Bus error in `array_management.cu`

### ISSUE THREAD

**Issue by szsdk** [eyalroz/cuda-api-wrappers#198] opened 2020-06-11 00:29 UTC
Does `device.synchronize();` missed in 
https://github.com/eyalroz/cuda-api-wrappers/blob/36c0fa021ceacfe96548636d3716913e009634b6/examples/other/array_management.cu#L162
?
If I do not add this, I will get a bus error.
But it is just a simple copy. I actually do not except a `synchronize` here.

**Comment by eyalroz** [comment] 2020-06-11 07:18
Well, those are 2 synchronous copy operations... and a "bus error" is a weird error to get :-(

Can you tell me more about your hardware environment?

**Comment by szsdk** [comment] 2020-06-11 08:35
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.64       Driver Version: 430.64       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980     Off  | 00000000:02:00.0  On |                  N/A |
| 11%   46C    P8    19W / 195W |    517MiB /  4043MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 980     Off  | 00000000:81:00.0 Off |                  N/A |
|  0%   39C    P8    17W / 195W |    300MiB /  4043MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```
I compile it with `nvcc array_management.cu  -I/home/username/.local/include  -std=c++14`.

**Comment by eyalroz** [comment] 2020-06-11 10:18
So, I'm inclined to say that it is "NOT MY FAULT (TM)", and that you would get the same behavior using the C Runtime API. 

But - let's try something else. Can you try cutting out as much of the program before those two copies and the bus error, so that you still get it? And also cut out everything afterwards? With a smaller program, I'll then convert it to just the C Runtime API, and see if we really hit the same problem. In that case I could ask elsewhere (e.g. the nVIDIA forums).

**Comment by szsdk** [comment] 2020-06-11 13:18
Strange, when I use the C Runtime API directly, it works.

This is the cuda-api-wrappers version:
```cuda
#include <cuda/api_wrappers.hpp>

#include <iostream>
#include <iomanip>
#include <numeric>
#include <limits>

using std::size_t;

template <typename T>
void check_output_is_iota(std::string name, const T* actual, size_t length) noexcept
{
	bool failed { false };
	for (size_t i = 0; i < length; ++i) {
		if (actual[i] != i) {
			if (not failed) {
				std::cerr << name << ": Output does not matched expected values:\n";
			}
			std::cerr << "output[" << std::setw(3) << i << "] = " << actual[i] << " != " << i << '\n';
		}
	}
	if (failed) { std::cerr << '\n'; }
}

template<class Device>
void array_2d_example(Device& device, size_t w, size_t h)
{
	namespace grid = cuda::grid;

	const cuda::array::dimensions_t<2> dims = {w, h};
	auto ptr_in = cuda::memory::managed::make_unique<float[]>(w * h);
	auto ptr_out = cuda::memory::managed::make_unique<float[]>(w * h);

  for(int i=0; i < w * h; i++) ptr_out.get()[i] = i;
	cuda::array_t<float, 2> other_arr(device, dims);
	cuda::memory::copy(other_arr, ptr_out.get());
	cuda::memory::copy(ptr_in.get(), other_arr);
  // Uncommenting next line makes things work
  //device.synchronize();

  check_output_is_iota("copy from (managed) global memory into a 2D array", ptr_in.get(), w * h);
}

int main()
{
	auto device = cuda::device::current::get();

	// array dimensions
	constexpr size_t w = 3;
	constexpr size_t h = 3;

	array_2d_example(device, w, h);
	device.synchronize();
  std::cout << "SUCCESS\n";
}
```

C Runtime Version works without synchronization.
```cuda
#include <iostream>
#include <iomanip>
#include <numeric>
#include <limits>

using std::size_t;

template <typename T>
void check_output_is_iota(std::string name, const T* actual, size_t length) noexcept
{
	bool failed { false };
	for (size_t i = 0; i < length; ++i) {
		if (actual[i] != i) {
			if (not failed) {
				std::cerr << name << ": Output does not matched expected values:\n";
			}
			std::cerr << "output[" << std::setw(3) << i << "] = " << actual[i] << " != " << i << '\n';
		}
	}
	if (failed) { std::cerr << '\n'; }
}

int main()
{
	constexpr size_t w = 3;
	constexpr size_t h = 3;
  constexpr size_t whs = w * h * sizeof(float);

  float *ptr_in, *ptr_out;
	cudaArray *other_arr;

	auto channel_desc = cudaCreateChannelDesc<float>();
	auto status = cudaMallocArray(&other_arr, &channel_desc, w, h);

  cudaMallocHost((void **)&ptr_in, whs);
  cudaMallocHost((void **)&ptr_out, whs);
  for(int i=0; i < w * h; i++) ptr_out[i] = i;

  // cp from ptr_out to other_arr
	const auto width_in_bytes = sizeof(float) * w;
	const auto source_pitch = width_in_bytes;
	cudaMemcpy2DToArray(
          other_arr,
    0,
    0,
    ptr_out,
		source_pitch,
		width_in_bytes,
    h,
		cudaMemcpyDefault);
  // cp from other_arr to ptr_in
	const auto destination_pitch = width_in_bytes;
	cudaMemcpy2DFromArray(
          ptr_in,
		destination_pitch,
    other_arr,
    0,
    0,
		width_in_bytes,
    h,
		cudaMemcpyDefault);
  check_output_is_iota("copy from (managed) global memory into a 2D array", ptr_in, w * h);
  cudaFreeHost(ptr_in);
  cudaFreeHost(ptr_out);
  cudaFreeArray(other_arr);
  std::cout << "SUCCESS\n";
}
```

**Comment by eyalroz** [comment] 2020-06-11 13:41
Ok, now I just need to find some time to have a deeper look at this. Thank you.

**Comment by szsdk** [comment] 2020-06-11 14:12
You are welcome. And thank you for writing this amazing library. I hope I can find it earlier before I develop a big cuda package. I just read it from reddit this morning. As you can see, I am just running the examples.

**Comment by eyalroz** [comment] 2020-06-12 11:35
I can't reproduce.

Let me try and extract just the C API calls and see.

**Comment by eyalroz** [comment] 2020-06-12 12:33
Ah, well, here's the thing: You switched to C and used `cudaMallocHost()`, not `cudaMallocManaged()`.

**Comment by szsdk** [comment] 2020-06-12 12:40
Bad new it that I changed to `cudaMallocManaged()`, the C API version still sucess.
```cuda
#include <iostream>
#include <iomanip>
#include <numeric>
#include <limits>

using std::size_t;

template <typename T>
void check_output_is_iota(std::string name, const T* actual, size_t length) noexcept
{
	bool failed { false };
	for (size_t i = 0; i < length; ++i) {
		if (actual[i] != i) {
			if (not failed) {
				std::cerr << name << ": Output does not matched expected values:\n";
			}
			std::cerr << "output[" << std::setw(3) << i << "] = " << actual[i] << " != " << i << '\n';
		}
	}
	if (failed) { std::cerr << '\n'; }
}

int main()
{
	constexpr size_t w = 3;
	constexpr size_t h = 3;
  constexpr size_t whs = w * h * sizeof(float);

  float *ptr_in, *ptr_out;
	cudaArray *other_arr;

	auto channel_desc = cudaCreateChannelDesc<float>();
	auto status = cudaMallocArray(&other_arr, &channel_desc, w, h);

  cudaMallocManaged((void **)&ptr_in, whs);
  cudaMallocManaged((void **)&ptr_out, whs);
  for(int i=0; i < w * h; i++) ptr_out[i] = i;

  // cp from ptr_out to other_arr
	const auto width_in_bytes = sizeof(float) * w;
	const auto source_pitch = width_in_bytes;
	cudaMemcpy2DToArray(
          other_arr,
    0,
    0,
    ptr_out,
		source_pitch,
		width_in_bytes,
    h,
		cudaMemcpyDefault);
  // cp from other_arr to ptr_in
	const auto destination_pitch = width_in_bytes;
	cudaMemcpy2DFromArray(
          ptr_in,
		destination_pitch,
    other_arr,
    0,
    0,
		width_in_bytes,
    h,
		cudaMemcpyDefault);
  check_output_is_iota("copy from (managed) global memory into a 2D array", ptr_in, w * h);
  cudaFreeHost(ptr_in);
  cudaFreeHost(ptr_out);
  cudaFreeArray(other_arr);
  cudaPeekAtLastError();
  cudaDeviceSynchronize();
  std::cout << "SUCCESS\n";
}
```

**Comment by szsdk** [comment] 2020-06-12 12:56
I think it has something to do with `other_arr`. Because I try the following code. It has the same bus error.
```cuda
#include <cuda/api_wrappers.hpp>

#include <iostream>
#include <iomanip>
#include <numeric>
#include <limits>

using std::size_t;

template <typename T>
void check_output_is_iota(std::string name, const T* actual, size_t length) noexcept
{
	bool failed { false };
	for (size_t i = 0; i < length; ++i) {
		if (actual[i] != i) {
			if (not failed) {
				std::cerr << name << ": Output does not matched expected values:\n";
			}
			std::cerr << "output[" << std::setw(3) << i << "] = " << actual[i] << " != " << i << '\n';
		}
	}
	if (failed) { std::cerr << '\n'; }
}

template<class Device>
void array_2d_example(Device& device, size_t w, size_t h)
{
	namespace grid = cuda::grid;

  const cuda::array::dimensions_t<2> dims = {w, h};

  size_t whs = w * h * sizeof(float);
  float *ptr_out, *ptr_in;
  cudaMallocManaged((void **)&ptr_out, whs);
  cudaMallocManaged((void **)&ptr_in, whs);

  for(int i=0; i < w * h; i++) ptr_out[i] = i;
	cuda::array_t<float, 2> other_arr(device, dims);
	cuda::memory::copy(other_arr, ptr_out);
	cuda::memory::copy(ptr_in, other_arr);
  //device.synchronize();

  check_output_is_iota("copy from (managed) global memory into a 2D array", ptr_in, w * h);
}

int main()
{
	auto device = cuda::device::current::get();

	// array dimensions
	constexpr size_t w = 3;
	constexpr size_t h = 3;

	array_2d_example(device, w, h);
	device.synchronize();
  std::cout << "SUCCESS\n";
}
```

**Comment by eyalroz** [comment] 2020-06-12 13:01
@codecircuit : Christoph, you might also want to have a look at this.

**Comment by szsdk** [comment] 2020-06-12 13:06
Hi, guys. I futher narrow down the problem.
```cuda
include <cuda/api_wrappers.hpp>

#include <iostream>
#include <iomanip>
#include <numeric>
#include <limits>

using std::size_t;

template <typename T>
void check_output_is_iota(std::string name, const T* actual, size_t length) noexcept
{
	bool failed { false };
	for (size_t i = 0; i < length; ++i) {
		if (actual[i] != i) {
			if (not failed) {
				std::cerr << name << ": Output does not matched expected values:\n";
			}
			std::cerr << "output[" << std::setw(3) << i << "] = " << actual[i] << " != " << i << '\n';
		}
	}
	if (failed) { std::cerr << '\n'; }
}

template<class Device>
void array_2d_example(Device& device, size_t w, size_t h)
{
	namespace grid = cuda::grid;

  const cuda::array::dimensions_t<2> dims = {w, h};

  size_t whs = w * h * sizeof(float);
  float *ptr_out, *ptr_in;
  cudaMallocManaged((void **)&ptr_out, whs);
  cudaMallocManaged((void **)&ptr_in, whs);

  for(int i=0; i < w * h; i++) ptr_out[i] = i;
	cuda::array_t<float, 2> other_arr(device, dims);

	const auto width_in_bytes = sizeof(float) * w;

  cuda::memory::copy(other_arr, ptr_out);
  // !!!!!!!!!!!!!!!!!!!!!!!
  // Changing from true to false gives the bus error.
  if (true) {
    const auto destination_pitch = width_in_bytes;
    cudaMemcpy2DFromArray(
          ptr_in,
    destination_pitch,
    other_arr.get(),
    0,
    0,
    width_in_bytes,
    h,
    cudaMemcpyDefault);
  } else {
    cuda::memory::copy(ptr_in, other_arr);
    // !!!!!!!!!!!!!!!!!!!!!!!
    // Uncommenting the following line makes things work again.
    //device.synchronize();
  }

  check_output_is_iota("copy from (managed) global memory into a 2D array", ptr_in, w * h);
}

int main()
{
	auto device = cuda::device::current::get();

	// array dimensions
	constexpr size_t w = 3;
	constexpr size_t h = 3;

	array_2d_example(device, w, h);
	device.synchronize();
  std::cout << "SUCCESS\n";
}
```

**Comment by szsdk** [comment] 2020-06-12 13:18
I think I have catched the bug.
https://github.com/eyalroz/cuda-api-wrappers/blob/40ba1198e43e150f2f743868b21d1ea3a289f7f4/src/cuda/api/memory.hpp#L424
This line should be `cudaMemcpy2DFromArray`, right?

**Comment by eyalroz** [comment] 2020-06-12 18:31
@szsdk : Yes, you're right. Let me check the rest of the copy implementations as well.

**Comment by eyalroz** [comment] 2020-06-13 17:57
@szsdk : So, this is fixed on the development branch. In a few days I'll make a point release with the fix integrated.

**Comment by szsdk** [comment] 2020-06-13 22:35
@eyalroz Thanks. Please close the issue if you wish.

**Comment by eyalroz** [comment] 2020-06-15 07:12
@szsdk : I only close bugs when the fix lands on master.

**Closed** 2020-06-28 21:56 UTC
Labels: bug, fixed-on-development
